language: node_js
node_js:
- '8'
notifications:
  slack:
    secure: ieJ1GytS7ITDs2XTajHdf70iGDfNCYuJfz0s5+xXkEoWt6l/Ka+Wk8pbkXGj7VQxo0VrRR4uinwpRo/svXzTVSbr+UaKTDzVJ4SFKlHw3PUc8Kdkf2OjI/BjPjea85kSlQdrabNTa9wPURe0ltVfTuEpzepMubGoSXIkMONmiPBZXwnLqY8QcoOA+B2NjSSt6Vo3FDoOodHMQKH+agQY06OMn7GQ10OjAyxm2pBrgbZGzWY8y1G3Aeb4URgI0tR5C1Usur8SluotPUj9+eWzygdYtMnAPhbX9UD/r91r3A5W5SNuNHUKcRNKUc8LcRSs6dITptcxHttguzZzEeuYL1iyPnIhKUSizImjY2HOLStPDo+drbOhwKiypRUOvR5xe3V8Piz7Zv5Yht6epV3k5FUgl1BsO3rJEDXgvY5qX7UM0xA/aB5XDvvIn/RkAfEE0q8Admf/njTsW+CCQzmLK4uGuX0u6DArdz9dfDlaQCeWD/B+blLUOBZM6ndfnSNyQJpLrlrHH2/jM1cScFqGifl+ihLQ9ugEuU3Ysl9H4RoAZ0JUdTyqaQ0cBLr8tWoW4yL6CF+fUY++QB6fT2L7BkhPEOEuHeoFtBlJXl78zI0VJEPd87xx096HQ0RO2oWI4UWPYeFOnIpPqbP5exv2e/uNUAI7DXSnB7qGdiccKS8=
